DROP FUNCTION IF EXISTS MZ_GETNAMEMONTH;

DELIMITER //

CREATE FUNCTION MZ_GETNAMEMONTH( NMONTH int )
RETURNS varchar(15)
BEGIN
	
	CASE NMONTH  		
		WHEN 1 THEN return "GENNAIO";
		WHEN 2 THEN return "FEBBRAIO";
		WHEN 3 THEN return "MARZO";
		WHEN 4 THEN return "APRILE";
		WHEN 5 THEN return "MAGGIO";
		WHEN 6 THEN return "GIUGNO";
		WHEN 7 THEN return "LUGLIO";
		WHEN 8 THEN return "AGOSTO";
		WHEN 9 THEN return "SETTEMBRE";
		WHEN 10 THEN return "OTTOBRE";
		WHEN 11 THEN return "NOVEMBRE";
		WHEN 12 THEN return "DICEMBRE";
	END CASE;
	

END; //
DELIMITER ;