DROP FUNCTION IF EXISTS MZ_showERR;

DELIMITER //
CREATE FUNCTION MZ_showERR(ERR varchar(255) )
  RETURNS TEXT
  LANGUAGE SQL
BEGIN
  return replace(SUBSTRING(ERR,2, LENGTH(ERR)), "$", "\n");
END; //
DELIMITER ;