DROP PROCEDURE IF EXISTS MZ_spMONEYl_project;

DELIMITER //
CREATE PROCEDURE MZ_spMONEYl_project (		
		 in YEAR int
		,in PROJECTID varchar(36)
	    ,in APPID varchar(36)
)
BEGIN	 
	DECLARE maxYEAR INT;	 

	SET @APPID = APPID;	 
	SET @PROJECTID = PROJECTID;

	insert into tmpMONEY
		SELECT Y.YEAR, Y.M, Y.MONTH, U.USERID, U.USER, U.AVATAR, 0 MONEYIN, SUM( M.MONEY ) MONEYOUT
		FROM MZ_MONEY M
		INNER JOIN MZ_USERS U on	
				U.CDATE IS null		
			AND U.USERID = M.USERID
		INNER JOIN MZ_ITEMCOST C ON
				C.CDATE IS null
			AND C.APPID = @APPID
			AND C.ITEMCOSTID = M.ITEMCOSTID
			AND C.CTYPE = 'U'
		INNER JOIN MZ_PROJECT P ON
                P.CDATE IS null
			AND P.APPID = @APPID
			AND P.PROJECTID = M.PROJECTID
		CROSS JOIN tmpYEARS Y		   	
		WHERE M.CDATE IS null
		AND M.PROJECTID = @PROJECTID
		AND M.APPID = @APPID		
		AND M.VDATE <= Y.END
		AND M.VDATE >= Y.START
		GROUP BY Y.YEAR, Y.M, Y.MONTH, U.USERID, U.USER, U.AVATAR;
		
	select max( M ) + 1 into maxYEAR from tmpMONEY;

	insert into tmpMONEY
		SELECT YEAR, maxYEAR, 'TOTALE', U.USERID, U.USER, U.AVATAR, 0 MONEYIN,  SUM( M.MONEY ) MONEYOUT
		FROM MZ_MONEY M
		INNER JOIN MZ_USERS U on	
				U.CDATE IS null		
			AND U.USERID = M.USERID
		INNER JOIN MZ_ITEMCOST C ON
				C.CDATE IS null
			AND C.APPID = @APPID
			AND C.ITEMCOSTID = M.ITEMCOSTID
			AND C.CTYPE = 'U'
		INNER JOIN MZ_PROJECT P ON
                P.CDATE IS null
			AND P.APPID = @APPID
			AND P.PROJECTID = M.PROJECTID
		WHERE M.CDATE IS null
		AND M.APPID = @APPID		
		AND M.PROJECTID = @PROJECTID
		AND year( M.VDATE ) = YEAR			
		GROUP BY U.USERID, U.USER, U.AVATAR;
END; //
DELIMITER //