/*
 * Tabella APP USER
*/
DROP TABLE IF EXISTS MZ_APPUSER;

CREATE TABLE `MZ_APPUSER`(
  `APPUSERID` varchar(36) NOT NULL,
  `APPID` varchar(36) NOT NULL,
  `USERID` varchar(36) NOT NULL,  
  `IDATA` datetime NOT NULL,
  `UDATE` datetime DEFAULT NULL,
  `CDATE` datetime DEFAULT NULL,
  `DINI` datetime DEFAULT NULL,
  `DFIN` datetime DEFAULT NULL,
  `USERAPP` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`APPUSERID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

