/*
 * Tabella legame voci di costo utenti
*/ 
DROP TABLE IF EXISTS MZ_ITEMCOSTUSER;

CREATE TABLE `MZ_ITEMCOSTUSER` (
  `ITEMCOSTUSERID` varchar(36) NOT NULL,
  `ITEMCOSTID` varchar(36) NOT NULL,
  `USERID` varchar(36) NOT NULL,
  `IDATA` datetime NOT NULL,
  `UDATE` datetime DEFAULT NULL,
  `CDATE` datetime DEFAULT NULL,
  `DINI` datetime DEFAULT NULL,
  `DFIN` datetime DEFAULT NULL,
  `USERAPP` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ITEMCOSTUSERID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;