/*
 *  Tabella menu utente
 */

DROP TABLE IF EXISTS MZ_MENUUSER;

CREATE TABLE `MZ_MENUUSER`(
  `MENUID` varchar(36) NOT NULL,
  `USERID` varchar(36) NOT NULL,  
  `IDATA` datetime NOT NULL,
  `UDATE` datetime DEFAULT NULL,
  `CDATE` datetime DEFAULT NULL,
  `DINI` datetime DEFAULT NULL,
  `DFIN` datetime DEFAULT NULL,
  `USERAPP` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`MENUID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;