/*
 * Tabella Gruppi
*/ 
DROP TABLE IF EXISTS MZ_PROJECT;

CREATE TABLE MZ_PROJECT (
  PROJECTID varchar(36) NOT NULL,
  NAME varchar(255) NOT NULL,    
  IDATA datetime NOT NULL,
  UDATE datetime DEFAULT NULL,
  CDATE datetime DEFAULT NULL,
  DINI datetime DEFAULT NULL,
  DFIN datetime DEFAULT NULL,
  USERAPP varchar(45) DEFAULT NULL,
  PRIMARY KEY (PROJECTID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE MZ_PROJECT ADD  `APPID` varchar(36) NOT NULL;